import streamlit as st

# Title of App
st.title("Web Development Lab03")

# Assignment Data 
# TODO: Fill out your team number, section, and team members

st.header("CS 1301")
st.subheader("Team XX, Web Development - Section X")
st.subheader("Team Member 1, Team Member 2")


# Introduction
# TODO: Write a quick description for all of your pages in this lab below, in the form:
#       1. **Page Name**: Description
#       2. **Page Name**: Description
#       3. **Page Name**: Description
#       4. **Page Name**: Description

st.write("""
Welcome to our Streamlit Web Development Lab03 app! You can navigate between the pages using the sidebar to the left. The following pages are:

1. Nathan's Portfolio Page: An online Portfolio of Nathan's professional experience.
2. Jodany's Portfolio Page: An online Portfolio of Jodany's professional experience.
3. Find Free Game Page: A free game finder, after typing in whether the user wants one or multiple genres for the search,
offers game options and brief description. 
4. AI Free Game Analyzer: After finding the user's preferred game of choice they 
can then gain a more in depth game description generated by our AI game expert. 
Afterwards users can ask about tips when starting out and doing well in their game of choice.

""")

